-- MySQL Script generated by MySQL Workbench
-- Sat Mar 21 00:37:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eif209_2001_p01b
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eif209_2001_p01b` ;

-- -----------------------------------------------------
-- Schema eif209_2001_p01b
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eif209_2001_p01b` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `eif209_2001_p01b` ;

-- -----------------------------------------------------
-- Table `eif209_2001_p01b`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p01b`.`usuario` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p01b`.`usuario` (
  `id_usuario` INT NOT NULL,
  `clave_acceso` VARCHAR(45) NOT NULL,
  `clave_vencida` TINYINT NOT NULL DEFAULT 1,
  `rol` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p01b`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p01b`.`cliente` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p01b`.`cliente` (
  `id_cliente` VARCHAR(16) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `usuario_id_usuario_UNIQUE` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `eif209_2001_p01b`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p01b`.`moneda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p01b`.`moneda` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p01b`.`moneda` (
  `nombre` VARCHAR(3) NOT NULL,
  `descripcion` VARCHAR(20) NOT NULL,
  `simbolo` VARCHAR(4) NOT NULL,
  `tipo_cambio_compra` DOUBLE NOT NULL,
  `tipo_cambio_venta` DOUBLE NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p01b`.`tipo_cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p01b`.`tipo_cuenta` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p01b`.`tipo_cuenta` (
  `id_tipo_cuenta` INT NOT NULL,
  `descripción` VARCHAR(45) NOT NULL,
  `tasa_interés` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_tipo_cuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p01b`.`cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p01b`.`cuenta` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p01b`.`cuenta` (
  `num_cuenta` INT NOT NULL,
  `tipo_cuenta_id_tipo_cuenta` INT NOT NULL,
  `cliente_id_cliente` VARCHAR(16) NOT NULL,
  `moneda_nombre` VARCHAR(3) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `limite_transferencia_diaria` DOUBLE NOT NULL DEFAULT 1000000,
  `activa` TINYINT NOT NULL DEFAULT 1,
  `saldo_actual` DOUBLE NOT NULL DEFAULT 0,
  `fecha_ultima_aplicacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`num_cuenta`),
  INDEX `fk_cuenta_moneda_idx` (`moneda_nombre` ASC) VISIBLE,
  INDEX `fk_cuenta_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_cuenta_tipo_cuenta1_idx` (`tipo_cuenta_id_tipo_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_cuenta_moneda`
    FOREIGN KEY (`moneda_nombre`)
    REFERENCES `eif209_2001_p01b`.`moneda` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `eif209_2001_p01b`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_tipo_cuenta1`
    FOREIGN KEY (`tipo_cuenta_id_tipo_cuenta`)
    REFERENCES `eif209_2001_p01b`.`tipo_cuenta` (`id_tipo_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p01b`.`movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p01b`.`movimiento` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p01b`.`movimiento` (
  `id_movimiento` INT NOT NULL AUTO_INCREMENT,
  `cuenta_num_cuenta` INT NOT NULL,
  `monto` DOUBLE NOT NULL DEFAULT 0,
  `fecha` DATETIME NOT NULL DEFAULT NOW(),
  `detalle` VARCHAR(200) NULL DEFAULT 'NINGUNO',
  `depositante` VARCHAR(60) NULL DEFAULT 'dueño de la cueta',
  `aplicado` INT NULL DEFAULT 0,
  PRIMARY KEY (`id_movimiento`, `cuenta_num_cuenta`),
  INDEX `fk_movimiento_cuenta1_idx` (`cuenta_num_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_movimiento_cuenta1`
    FOREIGN KEY (`cuenta_num_cuenta`)
    REFERENCES `eif209_2001_p01b`.`cuenta` (`num_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p01b`.`favorita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p01b`.`favorita` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p01b`.`favorita` (
  `cliente_id_cliente` VARCHAR(16) NOT NULL,
  `cuenta_num_cuenta` INT NOT NULL,
  PRIMARY KEY (`cliente_id_cliente`, `cuenta_num_cuenta`),
  INDEX `fk_favorita_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_favorita_cuenta1_idx` (`cuenta_num_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_favorita_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `eif209_2001_p01b`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorita_cuenta1`
    FOREIGN KEY (`cuenta_num_cuenta`)
    REFERENCES `eif209_2001_p01b`.`cuenta` (`num_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p01b`.`transferencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p01b`.`transferencia` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p01b`.`transferencia` (
  `id_transferencia` INT NOT NULL AUTO_INCREMENT,
  `cuenta_origen` INT NOT NULL,
  `cuenta_destino` INT NOT NULL,
  `monto` VARCHAR(45) NOT NULL DEFAULT 0,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_transferencia`, `cuenta_origen`, `cuenta_destino`),
  INDEX `fk_transferencia_cuenta1_idx` (`cuenta_origen` ASC) VISIBLE,
  INDEX `fk_transferencia_cuenta2_idx` (`cuenta_destino` ASC) VISIBLE,
  CONSTRAINT `fk_transferencia_cuenta1`
    FOREIGN KEY (`cuenta_origen`)
    REFERENCES `eif209_2001_p01b`.`cuenta` (`num_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transferencia_cuenta2`
    FOREIGN KEY (`cuenta_destino`)
    REFERENCES `eif209_2001_p01b`.`cuenta` (`num_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
